### ISSUE TITLE
Adding richer titles

### ISSUE THREAD

**Issue by kiliansch** [nzbasic/osutracker#2]
Hi, i was browsing with the tracker, nice work btw, and wanted to go back to a certain entry, couldn't identify it tho because every title just says "osuTracker". Would be nice to have more information there.

![image](https://user-images.githubusercontent.com/13236022/111081771-3ecec100-8505-11eb-96a1-3cfe6b309963.png)

Cheers

**Comment by nzbasic** [comment]
Thanks for the feedback, I have updated the site to have rich titles based on the page data :)
