### ISSUE TITLE
Accounts registered multiple times

### ISSUE THREAD

**Issue by tortuguitado** [nzbasic/osutracker#3]
It seems some players have been registered in the tracker multiple times (Or at least thats what it looks like)
You probably knew this already but I'm pointing it out anyway :)
![Screenshot (7)](https://user-images.githubusercontent.com/80722862/111228789-929fdf80-85c3-11eb-9d60-f8405b25ca94.png)

![dwad](https://user-images.githubusercontent.com/80722862/111228893-be22ca00-85c3-11eb-9f17-3cb5dd773aaa.png)

**Comment by nzbasic** [comment]
Thanks for spotting.. turns out I left a return out of my add user script, so it was sending an error back but still adding them lol. I'll start cleaning up these extra users
