### ISSUE TITLE
add dark mode

### ISSUE THREAD

**Issue by thymue** [nzbasic/osutracker#5]
**Is your feature request related to a problem? Please describe.**
My eyes hurt

**Describe the solution you'd like**
Add dark mode button to the site which changes the site to dark mode
mby have a look at this too https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme

**Comment by nzbasic** [comment]
Added a dark mode toggle in the footer 
![image](https://user-images.githubusercontent.com/54062686/134132264-18df2bf4-99e8-48a8-a653-650f21bff373.png)
