### ISSUE TITLE
Misleading average tracked user level

### ISSUE THREAD

**Issue by dirtlxiv** [nzbasic/osutracker#8]
In the "Average tracked user" section on [https://osutracker.com/stats](https://osutracker.com/stats) we are given profile level (97.20 at time of writing). We are also given pp and play count among other things.
For a profile with 60515 plays and 6487pp having a profile level of 97 is very unlikely. 

I would recommend calculating average ranked score, then converting to level. This would result in the "Average tracked user" stats being more realistic and comparable to an individuals profile.

**Comment by dirtlxiv** [comment]
Level is no longer displayed in average user stats

**Comment by nzbasic** [comment]
Removed for now, I agree that it does not make sense, it might appear later
